CREATE TABLE [dbo].[AuditHistory] (
    [AuditHistoryID]            INT            IDENTITY (1, 1) NOT NULL,
    [UserID]                    NVARCHAR (MAX) NULL,
    [AuditName]                 NVARCHAR (MAX) NULL,
    [AuditImage]                NVARCHAR (MAX) NULL,
    [AuditLocation]             NVARCHAR (MAX) NULL,
    [AuditCity]                 NVARCHAR (MAX) NULL,
    [AuditStartDateTime]        DATETIME2 (7)  NOT NULL,
    [AuditEndDateTime]          DATETIME2 (7)  NOT NULL,
    [AuditedBy]                 NVARCHAR (MAX) NULL,
    [AssignedBy]                NVARCHAR (MAX) NULL,
    [AuditStatus]               NVARCHAR (MAX) NULL,
    [AuditType]                 NVARCHAR (MAX) NULL,
    [AuditCategory]             NVARCHAR (MAX) NULL,
    [TotalNumberOfChecklist]    INT            NOT NULL,
    [TotalOpenChecklist]        INT            NOT NULL,
    [TotalDraftChecklist]       INT            NOT NULL,
    [TotalClosedChecklist]      INT            NOT NULL,
    [TotalNoOfChecks]           INT            NOT NULL,
    [TotalYesChecks]            INT            NOT NULL,
    [TotalNoChecks]             INT            NOT NULL,
    [AuditScore]                INT            NOT NULL,
    [AuditMaxScore]             INT            NOT NULL,
    [AuditCompliancePercentage] FLOAT (53)     NOT NULL,
    [Submitted]                 BIT            NOT NULL,
    [SubmittedDateTime]         DATETIME2 (7)  NOT NULL,
    [Locked]                    BIT            NOT NULL,
    [Synced]                    BIT            NOT NULL,
    [SyncedDateTime]            DATETIME2 (7)  NOT NULL,
    [ModifiedBy]                NVARCHAR (MAX) NULL,
    [ModifiedDateTime]          DATETIME2 (7)  NOT NULL,
    [AuditID]                   INT            NULL,
    [CertificateID]             INT            NULL,
    CONSTRAINT [PK_AuditHistory] PRIMARY KEY CLUSTERED ([AuditHistoryID] ASC),
    CONSTRAINT [FK_AuditHistory_Audit_AuditID] FOREIGN KEY ([AuditID]) REFERENCES [dbo].[Audit] ([AuditID])
);

