CREATE TABLE [dbo].[Audit] (
    [AuditID]                     INT            IDENTITY (1, 1) NOT NULL,
    [AuditName]                   NVARCHAR (MAX) NULL,
    [AuditImage]                  NVARCHAR (MAX) NULL,
    [AuditCode]                   NVARCHAR (MAX) NULL,
    [AuditScheduledStartDateTime] DATETIME2 (7)  NOT NULL,
    [AuditScheduledEndDateTime]   DATETIME2 (7)  NOT NULL,
    [AuditStartDateTime]          DATETIME2 (7)  NOT NULL,
    [AuditEndDateTime]            DATETIME2 (7)  NOT NULL,
    [AuditedBy]                   NVARCHAR (MAX) NULL,
    [AuditedByRole]               NVARCHAR (MAX) NULL,
    [AssignedBy]                  NVARCHAR (MAX) NULL,
    [AssignedDateTime]            DATETIME2 (7)  NOT NULL,
    [AuditStatus]                 NVARCHAR (MAX) NULL,
    [AuditType]                   NVARCHAR (MAX) NULL,
    [AuditCategory]               NVARCHAR (MAX) NULL,
    [AuditObservation]            NVARCHAR (MAX) NULL,
    [TotalNumberOfChecklist]      INT            NOT NULL,
    [TotalOpenChecklist]          INT            NOT NULL,
    [TotalDraftChecklist]         INT            NOT NULL,
    [TotalClosedChecklist]        INT            NOT NULL,
    [TotalNoOfChecks]             INT            NOT NULL,
    [TotalYesChecks]              INT            NOT NULL,
    [TotalNoChecks]               INT            NOT NULL,
    [AuditScore]                  FLOAT (53)     NOT NULL,
    [AuditMaxScore]               FLOAT (53)     NOT NULL,
    [AuditCompliancePercentage]   FLOAT (53)     NOT NULL,
    [Submitted]                   BIT            NOT NULL,
    [SubmittedDateTime]           DATETIME2 (7)  NOT NULL,
    [Locked]                      BIT            NOT NULL,
    [Synced]                      BIT            NOT NULL,
    [SyncedDateTime]              DATETIME2 (7)  NOT NULL,
    [CertificateID]               INT            NULL,
    [ScheduleID]                  INT            NULL,
    [UserChecklistAuditInfoID]    INT            NULL,
    [LastModifiedBy]              NVARCHAR (MAX) NULL,
    [LastModifiedDateTime]        DATETIME2 (7)  NULL,
    [CreatedDateTime]             DATETIME2 (7)  NULL,
    [CreatedBy]                   NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_Audit] PRIMARY KEY CLUSTERED ([AuditID] ASC),
    CONSTRAINT [FK_Audit_Certificate_CertificateID] FOREIGN KEY ([CertificateID]) REFERENCES [dbo].[Certificate] ([CertificateID]),
    CONSTRAINT [FK_Audit_Schedule_ScheduleID] FOREIGN KEY ([ScheduleID]) REFERENCES [dbo].[Schedule] ([ScheduleID]),
    CONSTRAINT [FK_Audit_UserChecklistAuditInfos_UserChecklistAuditInfoID] FOREIGN KEY ([UserChecklistAuditInfoID]) REFERENCES [dbo].[UserChecklistAuditInfos] ([UserChecklistAuditInfoID])
);

