CREATE TABLE [dbo].[AuditChecklistHistory] (
    [AuditChecklistHistoryID] INT            IDENTITY (1, 1) NOT NULL,
    [ChecklistName]           NVARCHAR (MAX) NULL,
    [ChecklistCode]           NVARCHAR (MAX) NULL,
    [ChecklistIcon]           NVARCHAR (MAX) NULL,
    [ChecklistDescription]    NVARCHAR (MAX) NULL,
    [ChecklistDepartment]     NVARCHAR (MAX) NULL,
    [ChecklistArea]           NVARCHAR (MAX) NULL,
    [ChecklistSubArea]        NVARCHAR (MAX) NULL,
    [ChecklistStatus]         NVARCHAR (MAX) NULL,
    [ChecklistCategory]       NVARCHAR (MAX) NULL,
    [ChecklistType]           NVARCHAR (MAX) NULL,
    [TotalNoOfChecks]         INT            NOT NULL,
    [TotalYesResponse]        INT            NOT NULL,
    [TotalNoResponse]         INT            NOT NULL,
    [TotalScore]              FLOAT (53)     NOT NULL,
    [MaxScore]                FLOAT (53)     NOT NULL,
    [CompliancePercentage]    FLOAT (53)     NOT NULL,
    [PerformedBy]             NVARCHAR (MAX) NULL,
    [PerformedRole]           NVARCHAR (MAX) NULL,
    [ChecklistStartDateTime]  DATETIME2 (7)  NOT NULL,
    [ChecklistEndDateTime]    DATETIME2 (7)  NOT NULL,
    [Submitted]               BIT            NOT NULL,
    [SubmittedDateTime]       DATETIME2 (7)  NOT NULL,
    [Synced]                  BIT            NOT NULL,
    [SyncedDateTime]          DATETIME2 (7)  NOT NULL,
    [Locked]                  BIT            NOT NULL,
    [Pinned]                  BIT            NOT NULL,
    [ModifiedBy]              NVARCHAR (MAX) NULL,
    [ModifiedDateTime]        DATETIME2 (7)  NOT NULL,
    [AuditChecklistID]        INT            NULL,
    [NotificationID]          INT            NULL,
    [ReminderID]              INT            NULL,
    CONSTRAINT [PK_AuditChecklistHistory] PRIMARY KEY CLUSTERED ([AuditChecklistHistoryID] ASC),
    CONSTRAINT [FK_AuditChecklistHistory_AuditChecklist_AuditChecklistID] FOREIGN KEY ([AuditChecklistID]) REFERENCES [dbo].[AuditChecklist] ([AuditChecklistID])
);

