CREATE TABLE [dbo].[Mart_AuditChecklistChecks24/12/2018] (
    [CheckCode]                     NVARCHAR (MAX) NULL,
    [CheckName]                     NVARCHAR (MAX) NULL,
    [CheckImage]                    NVARCHAR (MAX) NULL,
    [CheckResponse]                 NVARCHAR (MAX) NULL,
    [CheckAnswer]                   NVARCHAR (MAX) NULL,
    [PerformedDateTime]             DATETIME2 (7)  NOT NULL,
    [Remark]                        NVARCHAR (MAX) NULL,
    [CheckScore]                    INT            NOT NULL,
    [CheckType]                     NVARCHAR (MAX) NULL,
    [CheckCategory]                 NVARCHAR (MAX) NULL,
    [AuditCheckID]                  INT            NOT NULL,
    [ChecklistName]                 NVARCHAR (MAX) NULL,
    [AuditChecklistID]              INT            NOT NULL,
    [ChecklistCode]                 NVARCHAR (MAX) NULL,
    [ChecklistIcon]                 NVARCHAR (MAX) NULL,
    [ChecklistCategory]             NVARCHAR (MAX) NULL,
    [ChecklistType]                 NVARCHAR (MAX) NULL,
    [ChecklistDescription]          NVARCHAR (MAX) NULL,
    [ChecklistStartDateTime]        DATETIME2 (7)  NOT NULL,
    [ChecklistEndDateTime]          DATETIME2 (7)  NOT NULL,
    [ChecklistDepartment]           NVARCHAR (MAX) NULL,
    [ChecklistArea]                 NVARCHAR (MAX) NULL,
    [ChecklistSubArea]              NVARCHAR (MAX) NULL,
    [PerformedBy]                   NVARCHAR (MAX) NULL,
    [PerformedRole]                 NVARCHAR (MAX) NULL,
    [ChecklistStatus]               NVARCHAR (MAX) NULL,
    [TotalYesResponse]              INT            NOT NULL,
    [TotalNoResponse]               INT            NOT NULL,
    [TotalScore]                    FLOAT (53)     NOT NULL,
    [MaxScore]                      FLOAT (53)     NOT NULL,
    [ChecklistCompliancePercentage] FLOAT (53)     NOT NULL,
    [Pinned]                        BIT            NOT NULL,
    [AuditID]                       INT            NOT NULL,
    [AuditName]                     NVARCHAR (MAX) NULL,
    [AuditImage]                    NVARCHAR (MAX) NULL,
    [AuditCode]                     NVARCHAR (MAX) NULL,
    [AuditScheduledStartDateTime]   DATETIME2 (7)  NOT NULL,
    [AuditScheduledEndDateTime]     DATETIME2 (7)  NOT NULL,
    [AuditStartDateTime]            DATETIME2 (7)  NOT NULL,
    [AuditEndDateTime]              DATETIME2 (7)  NOT NULL,
    [AuditedBy]                     NVARCHAR (MAX) NULL,
    [AuditedByRole]                 NVARCHAR (MAX) NULL,
    [AssignedBy]                    NVARCHAR (MAX) NULL,
    [AssignedDateTime]              DATETIME2 (7)  NOT NULL,
    [AuditStatus]                   NVARCHAR (MAX) NULL,
    [AuditType]                     NVARCHAR (MAX) NULL,
    [AuditCategory]                 NVARCHAR (MAX) NULL,
    [AuditObservation]              NVARCHAR (MAX) NULL,
    [TotalNumberOfChecklist]        INT            NOT NULL,
    [TotalOpenChecklist]            INT            NOT NULL,
    [TotalDraftChecklist]           INT            NOT NULL,
    [TotalClosedChecklist]          INT            NOT NULL,
    [TotalNoOfChecks]               INT            NOT NULL,
    [TotalYesChecks]                INT            NOT NULL,
    [TotalNoChecks]                 INT            NOT NULL,
    [AuditScore]                    INT            NOT NULL,
    [AuditMaxScore]                 INT            NOT NULL,
    [AuditCompliancePercentage]     FLOAT (53)     NOT NULL,
    [Submitted]                     BIT            NOT NULL,
    [SubmittedDateTime]             DATETIME2 (7)  NOT NULL,
    [Locked]                        BIT            NOT NULL,
    [Synced]                        BIT            NOT NULL,
    [SyncedDateTime]                DATETIME2 (7)  NOT NULL,
    [CertificateID]                 INT            NULL,
    [ScheduleID]                    INT            NULL,
    [UserChecklistAuditInfoID]      INT            NULL
);

